[project]
name = "odoo-addons-sygel-technology-sy-stock-logistics-reporting"
version = "17.0.20241220.0"
dependencies = [
    "odoo-addon-product_label_format_restrict>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
