[project]
name = "odoo-addons-sygel-technology-sy-stock-logistics-reporting"
version = "17.0.20250529.0"
dependencies = [
    "odoo-addon-delivery_slip_packages>=17.0dev,<17.1dev",
    "odoo-addon-picking_report_shipping_ref>=17.0dev,<17.1dev",
    "odoo-addon-picking_report_show_chained>=17.0dev,<17.1dev",
    "odoo-addon-product_label_format_restrict>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
