[project]
name = "odoo-addons-sygel-technology-sy-stock-logistics-reporting"
version = "18.0.20260723.0"
dependencies = [
    "odoo-addon-stock_picking_phytosanitary_report==18.0.*",
    "odoo-addon-stock_picking_report_valued_copy_unvalued==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
